spring.application.name=svc-catalogo
server.port=8081

spring.datasource.url=jdbc:postgresql://db-catalogo:5432/mercado_catalogo_db
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.jpa.hibernate.ddl-auto=update

# Habilitar Actuator para los Healthchecks de Docker Compose
management.endpoints.web.exposure.include=health
management.endpoint.health.show-details=always