spring.application.name=svc-pedidos
server.port=8082

spring.datasource.url=jdbc:postgresql://db-pedidos:5432/mercado_pedidos_db
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.jpa.hibernate.ddl-auto=update

# Habilitar Actuator para los Healthchecks de Docker Compose
management.endpoints.web.exposure.include=health
management.endpoint.health.show-details=always